import React from 'react';

const InternationalAboutSlide = () => (
<div className="international-container wow fadeIn">
	<div className="container">
		<div className="row">
			<div className="col-sm-12 section-description wow fadeIn">
				<h2 className="title">
					A Real Shared Economy, <br/>
					Owned by the World
				</h2>
				<div className="divider-1 wow fadeInUp">
					<span/>
				</div>
				<p className="description wow fadeInLeft m-t-60">
					Globle will be a real shared economy, owned equally by all its users. Anyone can
					create a account and become a Globle user, entirely free of charge.
				</p>
				<p className="description wow fadeInRight m-t-60">
					Contributors to projects, such as project creators, leads and team members will
					be fairly rewarded with the funds raised through crowdsales, as well as royalties
					on projects when they start to generate profits. Investors receive project tokens,
					which give them voting rights and a share of profits as well.
				</p>
				<p className="description wow fadeInLeft m-t-60">
					The rest of the profits will be funneled back to the platform. All such profits
					generated by Globle will then be redistributed equally to all its users, in the form
					of a basic income .
				</p>
			</div>
		</div>
	</div>
</div>
);

export default InternationalAboutSlide;
