import React from 'react';
import { Link } from 'react-router-dom';

const IntroductionHomeSlide = () => (
	<div id="introduction" className="section introduction-container">
		<div id="fp-nav" className="left wow fadeInDown primary">
			<ul>
				<li>
					<a href="#welcome">
						<span/>
					</a>
					<div className="fp-tooltip left">Welcome</div>
				</li>
				<li>
					<a href="#introduction" className="active">
						<span/>
					</a>
					<div className="fp-tooltip left">Introduction</div>
				</li>
				<li>
					<a href="#technology">
						<span/>
					</a>
					<div className="fp-tooltip left">Technology</div>
				</li>
				<li>
					<a href="#subscribe">
						<span/>
					</a>
					<div className="fp-tooltip left">Subscribe</div>
				</li>
			</ul>
		</div>
		<div className="container">
			<img className="concept-mobile-img" src="/assets/img/core/concept.png" alt="Concept"/>
			<div className="row">
				<div className="col-sm-12">
					<div className="concept-img"/>
				</div>
			</div>
			<div className="row">
				<div className="col-sm-12 call-to-action section-description wow fadeInLeftBig">
					<h2 className="title">Introducing Globle</h2>
					<p>
						Globle is a platform that fully democratizes the creation, development, funding, and
						management of new projects and ideas. It is a decentralized means of building and
						running new companies, a platform which is managed and owned equally by all its
						users. All profits generated by Globle projects are distributed between project
						contributors and the rest of Globle users, providing a potential universal basic income
						(UBI) to everyone.
					</p>
				</div>
			</div>
			<div className="row">
				<div className="col-sm-12 section-bottom-button wow fadeInUp">
					{/* <a className="block-link" href="#">Watch video</a> <br/> <br/> */}
					<Link className="btn btn-primary" to="about">
						Read more
					</Link>
				</div>
			</div>
		</div>
		<a className="anchor-link primary" href="#technology">
			<div className="inner">Scroll</div>
		</a>
	</div>
);

export default IntroductionHomeSlide;
